name: test-asy-windows
on:
  workflow_call:

# this job is meant to be called once build-asy-linux is done
jobs:
  test-x64-cxxtests:
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: ./.github/actions/initialize-linux-env
      - name: Download test artifacts
        uses: actions/download-artifact@v4
        with:
          name: asy-testfiles
          path: cmake-build-linux/release/
      - name: Download artifacts for gtest
        uses: actions/download-artifact@v4
        with:
          name: asy-gtest-files
          path: cmake-build-linux/release/cxxtests
      - run: chmod +x cmake-build-linux/release/cxxtests/asyCxxTests
      - name: google test
        run: ctest --test-dir cmake-build-linux/release -R "^cxxtests."
  test-x64-asy-tests:
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - run: sudo apt-get update && sudo apt-get install ghostscript
      - uses: ./.github/actions/initialize-linux-env
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: asy-buildfiles
          path: cmake-build-linux/release/
      - name: Download test artifacts
        uses: actions/download-artifact@v4
        with:
          name: asy-testfiles
          path: cmake-build-linux/release/
      - run: chmod +x cmake-build-linux/release/asy
      - name: asy test
        run: ctest --test-dir cmake-build-linux/release -R "^asy\..*" -E "asy\.(gc\..*|pic\.trans|gs\.ghostscript)"
      - name: wce test
        run: ctest --test-dir cmake-build-linux/release -R "^wce"
